Fix boost compilation and linking issues with recent clang (#2662)
Fix two boost issues, compilation and linkings issues with clang 18+,
and more.

* We used `add_compile_options(-DBOOST_ASIO_DISABLE_CONCEPTS)` in cmake
which led to `/usr/include/boost/asio/co_composed.hpp:849:13: error:
'async_operation' has not been declared`. Removing it works just fine,
was apparently fixed in boost 1.73
(https://github.com/boostorg/beast/issues/1884#issuecomment-635855251).
We require 1.81+.
 * Ignore a recent warning of Clang 18/19
 * With cmake 3.30+ we no longer need `FindModule` for boost:
    ```
    Upstream Boost 1.70
   and above provide a ``BoostConfig.cmake`` package configuration file.
   ``find_package(Boost CONFIG)`` finds the upstream package directly,
   without the find module.
   ```
 * fix templating issues in the Postgres protocol handler with clang 18+
* updated CI macs to Sonoma and changed linking of `hyriseSystemTest`
which made problems with macOS (`ld` works, but ld64.lld has issues for
whatever reason); using LLVM 19 now
 * update two third-party modules to get rid of some cmake warnings

---------

Co-authored-by: Bouncner <martin+github@boissier.de>
Co-authored-by: Martin Boissier <martin.boissier@hpi.de>
Co-authored-by: Daniel Lindner <27929897+dey4ss@users.noreply.github.com>